package org.jlab.phaser.swing.dialog.chooser;

import java.awt.Dialog;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import org.jlab.phaser.model.JobFilter;
import org.jlab.phaser.swing.PhaserClientFrame;
import org.jlab.phaser.swing.dialog.ResultsDialog;
import org.jlab.phaser.swing.util.ClearableMaskFormatter;

/**
 * The graphical dialog interface for the JobFilter chooser.
 * 
 * Layout was done using Netbeans Matisse Swing GUI builder.
 * 
 * @author ryans
 */
public class JobFilterChooserDialog extends ChooserDialog<JobFilter> {

    private static final Logger LOGGER = Logger.getLogger(JobFilterChooserDialog.class.getName());

    private boolean okPressed = false;

    /**
     * Creates new form ResultFilterChooserDialog
     *
     * @param parent The parent dialog
     */
    public JobFilterChooserDialog(Dialog parent) {
        super(parent);
        initComponents();

        try {
            ClearableMaskFormatter formatter = new ClearableMaskFormatter("##-U??-#### ##:##");
            jobsMinDateFilter.setFormatterFactory(new DefaultFormatterFactory(
                    formatter));
            formatter = new ClearableMaskFormatter("##-U??-#### ##:##");
            jobsMaxDateFilter.setFormatterFactory(new DefaultFormatterFactory(
                    formatter));
        } catch (ParseException e) {
            LOGGER.log(Level.SEVERE,
                    "Unable to set formatter factory for date filter input field",
                    e);
        }

        clearForm();
    }
    
    /**
     * Clears the chooser form.
     */
    public final void clearForm() {
        jobsJobIdFilter.setText("");
        jobsMinDateFilter.setValue(null);
        jobsMaxDateFilter.setValue(null);       
    }

    @Override
    public boolean isOkPressed() {
        return okPressed;
    }

    @Override
    public JobFilter getSelected() {
        Long jobId = null;

        String jobIdStr = jobsJobIdFilter.getText();
        try {
            if (jobIdStr != null && !jobIdStr.isEmpty()) {
                jobId = Long.valueOf(jobIdStr);
            }
        } catch (NumberFormatException e) {
            LOGGER.log(Level.WARNING, "Unable to parse job ID filter", e);
        }

        Date minJobStartDate = null;
        Date maxJobStartDate = null;

        SimpleDateFormat formatter = new SimpleDateFormat(PhaserClientFrame.TIMESTAMP_FORMAT);
        String minStr = (String) jobsMinDateFilter.getValue();
        String maxStr = (String) jobsMaxDateFilter.getValue();

        try {
            if (minStr != null && !minStr.isEmpty()) {
                minJobStartDate = formatter.parse(minStr);
            }
        } catch (ParseException e) {
            LOGGER.log(Level.WARNING,
                    "Unable to parse min job start date filter", e);
        }

        try {
            if (maxStr != null && !maxStr.isEmpty()) {
                maxJobStartDate = formatter.parse(maxStr);
            }
        } catch (ParseException e) {
            LOGGER.log(Level.WARNING,
                    "Unable to parse max job start date filter", e);
        }

        return new JobFilter(jobId, minJobStartDate, maxJobStartDate);
    }

    @Override
    public void setInitiallySelected(JobFilter selected) {
        SimpleDateFormat formatter = new SimpleDateFormat(PhaserClientFrame.TIMESTAMP_FORMAT);
        
        jobsJobIdFilter.setText(selected.getJobId() == null ? null : selected.getJobId().toString());
        jobsMinDateFilter.setValue(selected.getMinJobStartDate() == null ? null : formatter.format(selected.getMinJobStartDate()));
        jobsMaxDateFilter.setValue(selected.getMaxJobStartDate() == null ? null : formatter.format(selected.getMaxJobStartDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jobsJobIdFilter = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jobsMinDateFilter = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jobsMaxDateFilter = new javax.swing.JFormattedTextField();
        jobsMinDateChooserButton = new javax.swing.JButton();
        jobsMaxDateChooserButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Job Filter Chooser");
        setResizable(false);
        setSize(new java.awt.Dimension(650, 350));

        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel10.setText("Job #:");

        jobsJobIdFilter.setDocument(new org.jlab.phaser.swing.document.JobIdDocument());
        jobsJobIdFilter.setFont(new java.awt.Font("Monospaced", 2, 11)); // NOI18N

        jLabel11.setText("Min Job Start Date:");

        try {
            jobsMinDateFilter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-U??-#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jobsMinDateFilter.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

        jLabel12.setText("Max Job Start Date:");

        try {
            jobsMaxDateFilter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-U??-#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jobsMaxDateFilter.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

        jobsMinDateChooserButton.setText("Choose...");
        jobsMinDateChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobsMinDateChooserButtonActionPerformed(evt);
            }
        });

        jobsMaxDateChooserButton.setText("Choose...");
        jobsMaxDateChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobsMaxDateChooserButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("DD-MMM-YYYY hh:mm");

        jLabel13.setText("DD-MMM-YYYY hh:mm");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jobsJobIdFilter)
                    .addComponent(jobsMinDateFilter)
                    .addComponent(jobsMaxDateFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jobsMinDateChooserButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jobsMaxDateChooserButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addContainerGap(145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jobsJobIdFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clearButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jobsMinDateFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobsMinDateChooserButton)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jobsMaxDateFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobsMaxDateChooserButton)
                    .addComponent(jLabel13))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        okPressed = true;
        dispose();
    }//GEN-LAST:event_selectButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void clearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormActionPerformed
        clearForm();
    }//GEN-LAST:event_clearFormActionPerformed

    private void jobsMinDateChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobsMinDateChooserButtonActionPerformed
        TimestampChooser chooser = new TimestampChooser(this, PhaserClientFrame.TIMESTAMP_FORMAT);
        chooser.setInitiallySelected((String) jobsMinDateFilter.getValue());
        int retval = chooser.showChooserDialog();

        if (retval == Chooser.APPROVE_OPTION) {
            String selected = chooser.getSelected();
            jobsMinDateFilter.setValue(selected);
        }
    }//GEN-LAST:event_jobsMinDateChooserButtonActionPerformed

    private void jobsMaxDateChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobsMaxDateChooserButtonActionPerformed
        TimestampChooser chooser = new TimestampChooser(this, PhaserClientFrame.TIMESTAMP_FORMAT);
        chooser.setInitiallySelected((String) jobsMaxDateFilter.getValue());
        int retval = chooser.showChooserDialog();

        if (retval == Chooser.APPROVE_OPTION) {
            String selected = chooser.getSelected();
            jobsMaxDateFilter.setValue(selected);
        }
    }//GEN-LAST:event_jobsMaxDateChooserButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jobsJobIdFilter;
    private javax.swing.JButton jobsMaxDateChooserButton;
    private javax.swing.JFormattedTextField jobsMaxDateFilter;
    private javax.swing.JButton jobsMinDateChooserButton;
    private javax.swing.JFormattedTextField jobsMinDateFilter;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
