alter session set container = XEPDB1;

ALTER SYSTEM SET db_create_file_dest = '/opt/oracle/oradata';

create tablespace PHASER;

CREATE USER "PHASER_OWNER" PROFILE "DEFAULT" IDENTIFIED BY "password" DEFAULT TABLESPACE "PHASER" ACCOUNT UNLOCK;
CREATE USER "PHASER_READER" PROFILE "DEFAULT" IDENTIFIED BY "password" DEFAULT TABLESPACE "PHASER" ACCOUNT UNLOCK;
CREATE USER "PHASER_WRITER" PROFILE "DEFAULT" IDENTIFIED BY "password" DEFAULT TABLESPACE "PHASER" ACCOUNT UNLOCK;

GRANT UNLIMITED TABLESPACE TO PHASER_OWNER;

GRANT CONNECT TO PHASER_OWNER;
GRANT CONNECT TO PHASER_READER;
GRANT CONNECT TO PHASER_WRITER;

grant create session to phaser_writer;
grant create session to phaser_reader;
